import {
  Activity,
  Camera,
  ChartColumn,
  Cloud,
  Cpu,
  Database,
  Eye,
  Film,
  Folder,
  FolderTree,
  Gauge,
  GitBranch,
  Globe,
  HardDrive,
  HeartPulse,
  House,
  KeyRound,
  Layers,
  LayoutDashboard,
  Link2,
  Lock,
  Monitor,
  MonitorSmartphone,
  Music,
  Network,
  Package,
  Radar,
  Route,
  Server,
  Settings,
  Shield,
  Sparkles,
  Terminal,
  TriangleAlert,
  Tv,
  Wifi,
  Workflow,
  Wrench,
  Boxes,
} from "lucide-vue-next";

export const ICON_BY_KEY = {
  home: House,
  house: House,
  дом: House,
  dom: House,
  route: Route,
  net: Network,
  network: Network,
  сеть: Network,
  dashboard: LayoutDashboard,
  infra: Server,
  infrastructure: Server,
  инфраструктура: Server,
  server: Server,
  core: Boxes,
  ops: Wrench,
  media: Tv,
  медиа: Tv,
  tv: Tv,
  iot: Cpu,
  cloud: Cloud,
  wifi: Wifi,
  monitor: Monitor,
  cockpit: MonitorSmartphone,
  proxmox: Server,
  grafana: ChartColumn,
  gitea: GitBranch,
  git: GitBranch,
  jellyfin: Film,
  navidrome: Music,
  tunnel: Radar,
  tunnels: Radar,
  stats: Gauge,
  services: Layers,
  service: Layers,
  health: HeartPulse,
  alerts: TriangleAlert,
  alert: TriangleAlert,
  security: Shield,
  auth: Lock,
  key: KeyRound,
  db: Database,
  database: Database,
  storage: HardDrive,
  link: Link2,
  iframe: Globe,
  terminal: Terminal,
  package: Package,
  music: Music,
  camera: Camera,
  eye: Eye,
  observability: Activity,
  workflow: Workflow,
  settings: Settings,
  spark: Sparkles,
};

export const ICON_RULES = [
  { re: /\b(home|house|dom|дом)\b/, icon: House },
  { re: /\b(net|network|route|vpn|edge|сеть|маршрут|туннел)\b/, icon: Network },
  {
    re: /\b(infra|server|cluster|pve|проксмокс|инфраструктур)\b/,
    icon: Server,
  },
  { re: /\b(media|tv|video|stream|jellyfin|медиа)\b/, icon: Film },
  { re: /\b(iot|sensor|home-assistant|умн|дом)\b/, icon: Cpu },
  { re: /\b(stat|metric|chart|grafana|аналит|monitor)\b/, icon: ChartColumn },
  { re: /\b(alert|error|warn|critical|ошиб|авар)\b/, icon: TriangleAlert },
  { re: /\b(health|status|pulse|heart|состояни)\b/, icon: HeartPulse },
  { re: /\b(auth|token|secret|lock|ключ|безопас)\b/, icon: Shield },
  { re: /\b(db|database|postgres|mysql|redis)\b/, icon: Database },
];

export const FALLBACK_ICONS = {
  page: LayoutDashboard,
  group: FolderTree,
  subgroup: Folder,
  itemLink: Link2,
  itemIframe: Globe,
  widget: Gauge,
};
